---
name: test github action behavior
on:
  pull_request:

jobs:
  passing_test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: pass
        run: ls README.md
